# name: assert.async() handled outside test
# command: ["qunit","drooling-extra-done-outside.js"]

TAP version 13
ok 1 extra done scheduled outside any test
1..1
# pass 1
# skip 0
# todo 0
# fail 0
Bail out! Error: Unexpected release of async pause after tests finished.
  ---
  message: |+
    Error: Unexpected release of async pause after tests finished.
    > Test: extra done scheduled outside any test [async #1]
  severity: failed
  stack: |
    Error: Unexpected release of async pause after tests finished.
    > Test: extra done scheduled outside any test [async #1]
        at qunit.js
        at internal
  ...

# exit code: 1